### ISSUE TITLE
TypeError: doDqicorr()

### ISSUE THREAD

**Issue by paultheastronomer** [spacetelescope/calcos#19]
Here I create the error:

```sh
Python 3.5.4 |Anaconda, Inc.| (default, Nov 20 2017, 18:44:38) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from costools import x1dcorr
The following tasks in the costools package can be run with TEAL:
         splittag                 timefilter                 x1dcorr
>>> x1dcorr.x1dcorr("temp_corrtag.fits", outdir="sliced/", update_input=True, find=True, cutoff=5., verbosity=2)
Input     /home/paw/science/betapic/COS/data/2014/temp_corrtag.fits
OutFlt    sliced/temp_flt.fits
OutCounts sliced/temp_counts.fits
x1d       sliced/temp_x1d.fits

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paw/code/anaconda3/envs/astroconda/lib/python3.5/site-packages/costools/x1dcorr.py", line 185, in x1dcorr
    verbosity=verbosity)
  File "/home/paw/code/anaconda3/envs/astroconda/lib/python3.5/site-packages/calcos/x1d.py", line 207, in extractSpec
    flt_list[i], counts_list[i])
  File "/home/paw/code/anaconda3/envs/astroconda/lib/python3.5/site-packages/calcos/x1d.py", line 448, in makeFltCounts
    phdr, headers[1], minmax_shift_dict)
TypeError: doDqicorr() missing 2 required positional arguments: 'traceprofile' and 'gti'
```

The same error occurs when not using astroconda too.

Is this where I submit error reports?
If nobody has time to fix this, could somebody point me in the right direction?
What code do I fork and work on to fix the issue myself?

Thanks.

**Comment by paultheastronomer** [comment]
This problem can be solved by adding `None` and `None` as inputs to the function `doDqicorr()`.

Now I get an `IOError` since the file: `zas1615jl_spot.fits` can't be found. I've downloaded all the data I could find under the program but the *_spot.fits file is not amongst the calibration files. Anybody know where I can find it?

**Comment by paultheastronomer** [comment]
The *spot.fits files and other calibration files can be found at [https://hst-crds.stsci.edu/](https://hst-crds.stsci.edu/).
