### ISSUE TITLE
Fix RTD problems

### ISSUE THREAD

**Issue by stscirij** [spacetelescope/calcos#203]
Processing /home/docs/checkouts/readthedocs.org/user_builds/calcos/checkouts/195
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 339, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 470, in collect_root_requirements
    requested_extras=(),
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 435, in _make_requirement_from_install_req
    version=None,
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    version=version,
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 287, in __init__
    version=version,
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 550, in _prepare_linked_requirement
    self.build_isolation,
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 47, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 106, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 83, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 173, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 92, in create_module
    return importlib.import_module('setuptools._distutils')
  File "/home/docs/checkouts/readthedocs.org/user_builds/calcos/envs/195/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'

**Comment by stscirij** [comment]
fixed in #204
